### ISSUE TITLE
pyasn 0.5.0rc1 breaks ldap3 2.9.1

### ISSUE THREAD

**Issue by mhils** [pyasn1/pyasn1#9]
Originally reported by @szemek in https://github.com/mitmproxy/mitmproxy/pull/5527:

```
[...]

    import ldap3
  File "/Users/szemek//mitmproxy/.venv/lib/python3.10/site-packages/ldap3-2.9.1-py3.10.egg/ldap3/__init__.py", line 141, in <module>
    from .core.connection import Connection
  File "/Users/szemek//mitmproxy/.venv/lib/python3.10/site-packages/ldap3-2.9.1-py3.10.egg/ldap3/core/connection.py", line 38, in <module>
    from ..extend import ExtendedOperationsRoot
  File "/Users/szemek//mitmproxy/.venv/lib/python3.10/site-packages/ldap3-2.9.1-py3.10.egg/ldap3/extend/__init__.py", line 29, in <module>
    from .microsoft.dirSync import DirSync
  File "/Users/szemek//mitmproxy/.venv/lib/python3.10/site-packages/ldap3-2.9.1-py3.10.egg/ldap3/extend/microsoft/dirSync.py", line 27, in <module>
    from ...protocol.microsoft import dir_sync_control, extended_dn_control, show_deleted_control
  File "/Users/szemek//mitmproxy/.venv/lib/python3.10/site-packages/ldap3-2.9.1-py3.10.egg/ldap3/protocol/microsoft.py", line 32, in <module>
    from .controls import build_control
  File "/Users/szemek//mitmproxy/.venv/lib/python3.10/site-packages/ldap3-2.9.1-py3.10.egg/ldap3/protocol/controls.py", line 27, in <module>
    from ..utils.asn1 import encode
  File "/Users/szemek//mitmproxy/.venv/lib/python3.10/site-packages/ldap3-2.9.1-py3.10.egg/ldap3/utils/asn1.py", line 50, in <module>
    from pyasn1.codec.ber.encoder import tagMap, typeMap, AbstractItemEncoder
ImportError: cannot import name 'tagMap' from 'pyasn1.codec.ber.encoder' (/Users/szemek//mitmproxy/.venv/lib/python3.10/site-packages/pyasn1-0.5.0rc1-py3.10.egg/pyasn1/codec/ber/encoder.py)
```

ldap3 issue: https://github.com/cannatag/ldap3/issues/1046

**Comment by tiran** [comment]
Regression was introduced in 93e11a2dfded950827ba3393b5a4562270a766da . Let's add some aliases.

**Comment by szemek** [comment]
@tiran reference to ldap3 https://github.com/cannatag/ldap3/blob/040e09fe37cf06801960d494dfadf0a6ed94e38f/ldap3/utils/asn1.py#L50-L55
It looks `tagMap` and `typeMap` were changed to `TAG_MAP`, `TYPE_MAP`.
