### ISSUE TITLE
Pyasn1 no longer accepts bytearray in any decoder

### ISSUE THREAD

**Issue by arambelo** [pyasn1/pyasn1#29]
Since 0.5.0, decoding serialized ASN1 from a `bytearray` is no longer possible.

This looks like it is introduced with `asSeekableStream()`.

```
def asSeekableStream(substrate):
    """Convert object to seekable byte-stream.

    Parameters
    ----------
    substrate: :py:class:`bytes` or :py:class:`io.IOBase` or :py:class:`univ.OctetString`

    Returns
    -------
    : :py:class:`io.IOBase`

    Raises
    ------
    : :py:class:`~pyasn1.error.PyAsn1Error`
        If the supplied substrate cannot be converted to a seekable stream.
    """
    if isinstance(substrate, io.BytesIO):
        return substrate

    elif isinstance(substrate, bytes):
        return io.BytesIO(substrate)

    elif isinstance(substrate, univ.OctetString):
        return io.BytesIO(substrate.asOctets())

    try:
        # Special case: impossible to set attributes on `file` built-in
        # XXX: broken, BufferedReader expects a "readable" attribute.
        if _PY2 and isinstance(substrate, file):
            return io.BufferedReader(substrate)

        elif substrate.seekable():  # Will fail for most invalid types
            return substrate

        else:
            return CachingStreamWrapper(substrate)

    except AttributeError:
        raise error.UnsupportedSubstrateError(
            "Cannot convert " + substrate.__class__.__name__ +
            " to a seekable bit stream.")
```

**Comment by droideck** [comment]
@arambelo Could you please specify the test case/reproducing steps?
I see no test case failures regarding the issue.

**Comment by arambelo** [comment]
Here is a concrete example:

```
$ ipython                                                                                                                                                                                                                                      23-04-20 13:48:54
Python 3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pyasn1.codec.der import decoder

In [2]: from pyasn1.type import univ

In [3]: oid_der_encoded = bytearray.fromhex('06082A8648CE3D040302')

In [4]: decoded, remainder = decoder.decode(oid_der_encoded, univ.ObjectIdentifier())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/Library/Python/3.9/lib/python/site-packages/pyasn1/codec/streaming.py:116, in asSeekableStream(substrate)
    114     return io.BufferedReader(substrate)
--> 116 elif substrate.seekable():  # Will fail for most invalid types
    117     return substrate

AttributeError: 'bytearray' object has no attribute 'seekable'

During handling of the above exception, another exception occurred:

UnsupportedSubstrateError                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 decoded, remainder = decoder.decode(oid_der_encoded, univ.ObjectIdentifier())

File ~/Library/Python/3.9/lib/python/site-packages/pyasn1/codec/ber/decoder.py:1998, in Decoder.__call__(cls, substrate, asn1Spec, **options)
   1939 @classmethod
   1940 def __call__(cls, substrate, asn1Spec=None, **options):
   1941     """Turns BER/CER/DER octet stream into an ASN.1 object.
   1942
   1943     Takes BER/CER/DER octet-stream in form of :py:class:`bytes` (Python 3)
   (...)
   1996
   1997     """
-> 1998     substrate = asSeekableStream(substrate)
   2000     streamingDecoder = cls.STREAMING_DECODER(
   2001         substrate, asn1Spec, **options)
   2003     for asn1Object in streamingDecoder:

File ~/Library/Python/3.9/lib/python/site-packages/pyasn1/codec/streaming.py:123, in asSeekableStream(substrate)
    120         return CachingStreamWrapper(substrate)
    122 except AttributeError:
--> 123     raise error.UnsupportedSubstrateError(
    124         "Cannot convert " + substrate.__class__.__name__ +
    125         " to a seekable bit stream.")

UnsupportedSubstrateError: Cannot convert bytearray to a seekable bit stream.
```

**Comment by arambelo** [comment]
The same example works fine in Pyasn1 <= 0.4.8:

```
$ ipython                                                                                                    23-04-20 13:51:37
Python 3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pyasn1.type import univ

In [2]: from pyasn1.codec.der import decoder

In [3]: oid_der_encoded = bytearray.fromhex('06082A8648CE3D040302')

In [4]: decoded, remainder = decoder.decode(oid_der_encoded, univ.ObjectIdentifier())

In [5]: decoded
Out[5]: <ObjectIdentifier value object, tagSet <TagSet object, tags 0:0:6>, payload [1.2.840.10045.4.3.2]>

In [6]: import pyasn1

In [7]: pyasn1.__version__
Out[7]: '0.4.8'
```

**Comment by Costya-Y** [comment]
We have the same issues. The entire pysnmp-related deployments are failing right now. I believe everyone using pysnmp is affected by this release.
Please clarify, can you reconsider changes in the 0.5.0 release to preserve backward compatibility?

**Comment by droideck** [comment]
@arambelo will it be possible for your project to use `bytes` instead? (which is a supported way now)
The BER decoder was refactored at this point - https://github.com/pyasn1/pyasn1/commit/93e11a2dfded950827ba3393b5a4562270a766da - I don't have enough capacity now to work on any improvements on top of that. But we welcome patches from the community. :)

**Comment by arambelo** [comment]
> @arambelo will it be possible for your project to use `bytes` instead? (which is a supported way now) The BER decoder was refactored at this point - [93e11a2](https://github.com/pyasn1/pyasn1/commit/93e11a2dfded950827ba3393b5a4562270a766da) - I don't have enough capacity now to work on any improvements on top of that. But we welcome patches from the community. :)

I did as much as I could in my libraries, but I cannot force this change upon my clients. 

As it seem that I am far from being the only one hitting this issue, I can only recommend the change suggested in https://github.com/pyasn1/pyasn1/pull/33

**Comment by droideck** [comment]
We got a new release that fixes the issue presumably. Please, check it and reopen the issue if you are still affected.

**Comment by lextm** [comment]
Just to update here that PySNMP ecosystem only relies `bytes` and does not require any change proposed in this issue or related pull requests.
